package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Game;
import org.mybatis.cdi.Mapper;

@Mapper
public interface GameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GAME
     *
     * @mbg.generated Thu Apr 06 15:36:56 EEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GAME
     *
     * @mbg.generated Thu Apr 06 15:36:56 EEST 2023
     */
    int insert(Game record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GAME
     *
     * @mbg.generated Thu Apr 06 15:36:56 EEST 2023
     */
    Game selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GAME
     *
     * @mbg.generated Thu Apr 06 15:36:56 EEST 2023
     */
    List<Game> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GAME
     *
     * @mbg.generated Thu Apr 06 15:36:56 EEST 2023
     */
    int updateByPrimaryKey(Game record);
}