package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Review;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ReviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.REVIEW
     *
     * @mbg.generated Thu Apr 06 15:36:56 EEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.REVIEW
     *
     * @mbg.generated Thu Apr 06 15:36:56 EEST 2023
     */
    int insert(Review record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.REVIEW
     *
     * @mbg.generated Thu Apr 06 15:36:56 EEST 2023
     */
    Review selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.REVIEW
     *
     * @mbg.generated Thu Apr 06 15:36:56 EEST 2023
     */
    List<Review> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.REVIEW
     *
     * @mbg.generated Thu Apr 06 15:36:56 EEST 2023
     */
    int updateByPrimaryKey(Review record);
}