package lt.vu.mybatis.model;

public class Review {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.REVIEW.ID
     *
     * @mbg.generated Thu Apr 06 15:36:56 EEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.REVIEW.CONTENT
     *
     * @mbg.generated Thu Apr 06 15:36:56 EEST 2023
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.REVIEW.NAME
     *
     * @mbg.generated Thu Apr 06 15:36:56 EEST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.REVIEW.RATING
     *
     * @mbg.generated Thu Apr 06 15:36:56 EEST 2023
     */
    private Integer rating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.REVIEW.GAME_ID
     *
     * @mbg.generated Thu Apr 06 15:36:56 EEST 2023
     */
    private Integer gameId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.REVIEW.ID
     *
     * @return the value of PUBLIC.REVIEW.ID
     *
     * @mbg.generated Thu Apr 06 15:36:56 EEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.REVIEW.ID
     *
     * @param id the value for PUBLIC.REVIEW.ID
     *
     * @mbg.generated Thu Apr 06 15:36:56 EEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.REVIEW.CONTENT
     *
     * @return the value of PUBLIC.REVIEW.CONTENT
     *
     * @mbg.generated Thu Apr 06 15:36:56 EEST 2023
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.REVIEW.CONTENT
     *
     * @param content the value for PUBLIC.REVIEW.CONTENT
     *
     * @mbg.generated Thu Apr 06 15:36:56 EEST 2023
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.REVIEW.NAME
     *
     * @return the value of PUBLIC.REVIEW.NAME
     *
     * @mbg.generated Thu Apr 06 15:36:56 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.REVIEW.NAME
     *
     * @param name the value for PUBLIC.REVIEW.NAME
     *
     * @mbg.generated Thu Apr 06 15:36:56 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.REVIEW.RATING
     *
     * @return the value of PUBLIC.REVIEW.RATING
     *
     * @mbg.generated Thu Apr 06 15:36:56 EEST 2023
     */
    public Integer getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.REVIEW.RATING
     *
     * @param rating the value for PUBLIC.REVIEW.RATING
     *
     * @mbg.generated Thu Apr 06 15:36:56 EEST 2023
     */
    public void setRating(Integer rating) {
        this.rating = rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.REVIEW.GAME_ID
     *
     * @return the value of PUBLIC.REVIEW.GAME_ID
     *
     * @mbg.generated Thu Apr 06 15:36:56 EEST 2023
     */
    public Integer getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.REVIEW.GAME_ID
     *
     * @param gameId the value for PUBLIC.REVIEW.GAME_ID
     *
     * @mbg.generated Thu Apr 06 15:36:56 EEST 2023
     */
    public void setGameId(Integer gameId) {
        this.gameId = gameId;
    }
}